[package]
name = "bar-changer"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
toml = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
text_io = "0.1.13"
